In [1]:
import numpy as np

In [2]:
import pandas as ps

In [3]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [4]:
print("view array :",a)

view array : [10 20 30 40 50]


In [5]:
print("Shape of array:",a.shape)

Shape of array: (5,)


In [6]:
c = ps.Series(['arul','sri','ganesh','shankar','ajay'])
print("view  pandas:",c)


view  pandas: 0       arul
1        sri
2     ganesh
3    shankar
4       ajay
dtype: str


In [24]:
d1 =np.array([23,34,45,67,89,29,87,67])
print("One Dimentional Array:",d1)

One Dimentional Array: [23 34 45 67 89 29 87 67]


In [9]:
import numpy as np

In [10]:
d2 =np.array([[23,43,43,23,34],[43,43,54,55,76]])
print("Two Dimentional Array:",d2)

Two Dimentional Array: [[23 43 43 23 34]
 [43 43 54 55 76]]


In [11]:
num3= np.zeros([2,4])
print("zeros in numpy",num3)

zeros in numpy [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
num4=np.ones([3,5])
print("ones in numpy",num4)

ones in numpy [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
